### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [C-uo/zsh-env#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by C-uo** [comment]
Thank you for adding my plugin to your project.

The license file has been added. The website you recommend is very helpful to me.
